[package]
name = "protodefc"
version = "0.1.0"
authors = ["HansiHE <hansihe@hansihe.com>"]

[dependencies]
json = "0.11.5"
error-chain = "0.10.0"

[lib]
name = "protodefc"
path = "src/lib.rs"

[[bin]]
name = "protodefc"
path = "src/protodefc.rs"